# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Open Savannah
tagline:          'Local brigade of Code for America'
description:      'A group of technologists, residents and government partners working together to build Savannah-area civic tech infrastructure.'
url:              http://github.io/carlvlewis/hyde
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
